name: Build example AAR

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build AAR
        run: ./gradlew assemble
        working-directory: build
      - name: Upload AAR
        uses: actions/upload-artifact@v1
        with:
          name: ammerPayLib.aar
          path: build/AmmerCardSdk-Android/app/build/outputs/aar/app-release.aar
#
#          name: Android CI
#
#          on:
#            push:
#              branches: [ "master" ]
#            pull_request:
#              branches: [ "master" ]
#
#          jobs:
#            build:
#
#              runs-on: ubuntu-latest
#
#              steps:
#                - uses: actions/checkout@v4
#                  with:
#                    submodules: true
#
#                - name: set up JDK 17
#                  uses: actions/setup-java@v4
#                  with:
#                    java-version: 17
#                    distribution: temurin
#                    cache: gradle
#
#                - name: Grant execute permission for gradlew
#                  run: chmod +x gradlew
#                - name: Build with Gradle
#                  run: ./gradlew build
